-- CREAZIONE DEL DATABASE
CREATE DATABASE IF NOT EXISTS WEB_DELIVERY;
USE WEB_DELIVERY;


CREATE TABLE UTENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    COGNOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    RUOLO ENUM('CLIENTE', 'ADMIN', 'STAFF') DEFAULT 'CLIENTE',,
    INDIRIZZO VARCHAR(255),
    TELEFONO VARCHAR(20)
);

CREATE TABLE GRUPPO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE INGREDIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODOTTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRIZIONE TEXT,
    PREZZO DECIMAL(10, 2) NOT NULL,
    PROCEDURA TEXT,
    TEMPO_PREPARAZIONE INT, -- ESPRESSO IN MINUTI
    IMMAGINE VARCHAR(255)   -- PERCORSO O URL DELL'IMMAGINE
);



-- RELAZIONE 'APPARTIENE' (1 GRUPPO -> N CARATTERISTICHE)
CREATE TABLE CARATTERISTICA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRIZIONE TEXT,
    PREZZO DECIMAL(10, 2),
    IS_DEFAULT BOOLEAN DEFAULT FALSE, -- RINOMINATO DA 'DEFAULT' PER EVITARE CONFLITTI SQL
    GRUPPO_ID INT NOT NULL,
    FOREIGN KEY (GRUPPO_ID) REFERENCES GRUPPO(ID) ON DELETE CASCADE
);

-- RELAZIONE 'EFFETTUA' (1 UTENTE -> N ORDINI)
CREATE TABLE ORDINE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_ORDINE DATE NOT NULL,
    ORARIO_CONSEGNA TIME,
    PREZZO DECIMAL(10, 2) NOT NULL,
    STATO VARCHAR(50) NOT NULL,
    METODO_PAGAMENTO VARCHAR(50),
    INDIRIZZO_CONSEGNA VARCHAR(255) NOT NULL,
    UTENTE_ID INT NOT NULL,
    FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID) ON DELETE CASCADE
);

-- ENTITÀ DEBOLE 'LOG_STATO' LEGATA DA 'REGISTRA' A ORDINE E UTENTE
CREATE TABLE LOG_STATO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATO_FROM VARCHAR(50),
    STATO_TO VARCHAR(50),
    ORDINE_ID INT NOT NULL,
    UTENTE_ID INT NOT NULL, -- UTENTE CHE HA EFFETTUATO L'AZIONE
    FOREIGN KEY (ORDINE_ID) REFERENCES ORDINE(ID) ON DELETE CASCADE,
    FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID) ON DELETE CASCADE
);



-- RELAZIONE 'CONTIENE' TRA PRODOTTO E INGREDIENTE (INCLUDE L'ATTRIBUTO 'QUANTITA')
CREATE TABLE PRODOTTO_INGREDIENTE (
    PRODOTTO_ID INT NOT NULL,
    INGREDIENTE_ID INT NOT NULL,
    QUANTITA VARCHAR(50), -- ES. '200G', '1 PIZZICO'
    PRIMARY KEY (PRODOTTO_ID, INGREDIENTE_ID),
    FOREIGN KEY (PRODOTTO_ID) REFERENCES PRODOTTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (INGREDIENTE_ID) REFERENCES INGREDIENTE(ID) ON DELETE CASCADE
);

-- RELAZIONE 'CARATTERIZZA' TRA PRODOTTO E CARATTERISTICA
CREATE TABLE PRODOTTO_CARATTERISTICA (
    PRODOTTO_ID INT NOT NULL,
    CARATTERISTICA_ID INT NOT NULL,
    PRIMARY KEY (PRODOTTO_ID, CARATTERISTICA_ID),
    FOREIGN KEY (PRODOTTO_ID) REFERENCES PRODOTTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (CARATTERISTICA_ID) REFERENCES CARATTERISTICA(ID) ON DELETE CASCADE
);

-- RELAZIONE 'CONTIENE' TRA ORDINE E PRODOTTO
CREATE TABLE ORDINE_PRODOTTO (
    ORDINE_ID INT NOT NULL,
    PRODOTTO_ID INT NOT NULL,
    
    PRIMARY KEY (ORDINE_ID, PRODOTTO